# utils/district_priors.py
# NFHS-5 district-level risk priors for Bayesian baseline adjustment.
#
# Purpose:
#   Adjust organ risk estimates based on the user's district/state prevalence
#   of hypertension, diabetes, tobacco use, and alcohol use from NFHS-5 (2019-21).
#
#   This is a WEAK Bayesian prior — it subtly adjusts baseline risk when the
#   user is from a high-prevalence area. It does NOT override lab-based calculations.
#
# Reference:
#   National Family Health Survey (NFHS-5), 2019-21, India.
#   Microdata available at: http://rchiips.org/nfhs/NFHS-5_FCTS/India.shtml
#
# National India averages (NFHS-5 factsheet):
#   HTN prevalence women 15+: ~26%
#   DM prevalence women 15+:  ~14%
#   Tobacco use women:        ~7%
#   Tobacco use men:          ~38%  (approximate from state data)
#   Alcohol use men:          ~22%

import json
from pathlib import Path

_DATA_DIR = Path(__file__).parent.parent / "data"
_DISTRICT_FILE       = _DATA_DIR / "district_risk_priors.json"
_STATE_FILE          = _DATA_DIR / "state_risk_priors.json"
# NFHS-5 derived district health priors (706 districts, generated by integrate_datasets.py)
_NFHS5_DISTRICT_FILE = _DATA_DIR / "india" / "population" / "district_health_priors.json"

# National NFHS-5 averages for normalisation
NATIONAL_AVERAGES = {
    'htn_prev_women': 0.26,
    'dm_prev_women':  0.14,
    'tobacco_women':  0.07,
    'alcohol_women':  0.02,
    'clean_fuel_pct': 0.59,
    'anaemia_women':  0.57,
}

_district_cache = None
_state_cache    = None
_nfhs5_cache    = None


def _load_nfhs5_districts():
    """Load NFHS-5 derived district priors (706 districts, generated by integrate_datasets.py)."""
    global _nfhs5_cache
    if _nfhs5_cache is None:
        try:
            with open(_NFHS5_DISTRICT_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                _nfhs5_cache = data.get('districts', {})
        except Exception:
            _nfhs5_cache = {}
    return _nfhs5_cache


def get_nfhs5_district_priors(district: str = None) -> dict:
    """
    Look up NFHS-5 district health priors for lungs/heart/kidney adjustment.
    Returns dict with: clean_fuel_pct, high_bp_women_pct, high_sugar_women_pct,
    composite_cardio_risk, indoor_air_pollution_risk, state, or None if not found.
    Source: NFHS-5 (2019-21), MoHFW India — 706 districts.
    """
    if not district:
        return None
    data = _load_nfhs5_districts()
    key  = _normalise_key(district)
    return data.get(key, None)


def _load_district():
    global _district_cache
    if _district_cache is None:
        try:
            with open(_DISTRICT_FILE, 'r', encoding='utf-8') as f:
                _district_cache = json.load(f)
        except Exception:
            _district_cache = {}
    return _district_cache


def _load_state():
    global _state_cache
    if _state_cache is None:
        try:
            with open(_STATE_FILE, 'r', encoding='utf-8') as f:
                _state_cache = json.load(f)
        except Exception:
            _state_cache = {}
    return _state_cache


def _normalise_key(s: str) -> str:
    return s.lower().strip().replace(' ', '_').replace('/', '_').replace('-', '_')


def get_priors(district: str = None, state: str = None) -> dict:
    """
    Look up NFHS-5 priors for a district or state.
    Falls back to state → national average if district not found.

    Returns dict with keys: htn_prev, dm_prev, tobacco_prev, alcohol_prev,
    clean_fuel_pct, anaemia_prev, source.
    """
    districts = _load_district()
    states    = _load_state()

    prior = None

    # 1. District lookup
    if district:
        key = _normalise_key(district)
        if key in districts:
            prior = districts[key]

    # 2. State fallback
    if prior is None and state:
        key = _normalise_key(state)
        if key in states:
            sp = states[key]
            # State data has raw column names — map to standard keys
            prior = _map_state_prior(sp)

    # 3. National average fallback
    if prior is None:
        return {
            'htn_prev':      NATIONAL_AVERAGES['htn_prev_women'],
            'dm_prev':       NATIONAL_AVERAGES['dm_prev_women'],
            'tobacco_prev':  NATIONAL_AVERAGES['tobacco_women'],
            'alcohol_prev':  NATIONAL_AVERAGES['alcohol_women'],
            'clean_fuel_pct': NATIONAL_AVERAGES['clean_fuel_pct'],
            'anaemia_prev':  NATIONAL_AVERAGES['anaemia_women'],
            'source':        'national_average',
        }

    return {
        'htn_prev':      prior.get('htn_prev_women') or NATIONAL_AVERAGES['htn_prev_women'],
        'dm_prev':       prior.get('dm_prev_women')  or NATIONAL_AVERAGES['dm_prev_women'],
        'tobacco_prev':  prior.get('tobacco_women')  or NATIONAL_AVERAGES['tobacco_women'],
        'alcohol_prev':  prior.get('alcohol_women')  or NATIONAL_AVERAGES['alcohol_women'],
        'clean_fuel_pct': prior.get('clean_fuel_pct') or NATIONAL_AVERAGES['clean_fuel_pct'],
        'anaemia_prev':  prior.get('anaemia_women')  or NATIONAL_AVERAGES['anaemia_women'],
        'source':        f"NFHS5:{prior.get('district_raw', prior.get('state_raw', 'district'))}",
    }


def _map_state_prior(sp: dict) -> dict:
    """Map state-level JSON (raw column-named keys) to standardised key names."""
    # State data has truncated column names (first 30 chars)
    def pick(*candidates):
        for c in candidates:
            if c in sp and sp[c] is not None:
                return sp[c]
        return None

    return {
        'htn_prev_women': pick(
            'Women age 15 years and above wih',
            'Women age 15 years and above wi'),
        'dm_prev_women': pick(
            'Women age 15 years and above wih',   # reused due to truncation
        ),
        'tobacco_women': pick(
            'Women age 15 years and above who'),
        'alcohol_women': pick(
            'Women age 15 years and above who'),  # same truncation issue
        'clean_fuel_pct': pick('Households using clean fuel for'),
        'anaemia_women':  None,
        'state_raw': sp.get('state_raw', ''),
    }


def cardiovascular_prior_adjustment(priors: dict, user_has_htn: bool,
                                    user_has_dm: bool) -> float:
    """
    Returns a small risk adjustment [−0.03, +0.06] based on regional HTN/DM
    prevalence vs national average.

    Logic:
      - If district has higher-than-national HTN prevalence AND user doesn't
        report hypertension, apply a small positive adjustment (missed diagnosis
        is more likely in high-prevalence areas).
      - If district has lower-than-national prevalence, apply a small negative
        adjustment (Bayesian prior).

    This is intentionally kept small (max ±6%) to not override clinical labs.
    """
    htn_excess  = (priors['htn_prev'] - NATIONAL_AVERAGES['htn_prev_women'])
    dm_excess   = (priors['dm_prev']  - NATIONAL_AVERAGES['dm_prev_women'])

    # Only adjust for undiagnosed condition likelihood
    htn_adj = htn_excess * 0.12 if not user_has_htn else htn_excess * 0.04
    dm_adj  = dm_excess  * 0.10 if not user_has_dm  else dm_excess  * 0.03

    adjustment = htn_adj + dm_adj
    return round(max(-0.03, min(0.06, adjustment)), 4)


def kidney_prior_adjustment(priors: dict, user_has_htn: bool,
                             user_has_dm: bool) -> float:
    """
    Similar adjustment for kidney risk based on DM and HTN prevalence.
    Diabetic nephropathy and hypertensive CKD are the top 2 causes of CKD in India.
    """
    htn_excess = priors['htn_prev'] - NATIONAL_AVERAGES['htn_prev_women']
    dm_excess  = priors['dm_prev']  - NATIONAL_AVERAGES['dm_prev_women']

    htn_adj = htn_excess * 0.10 if not user_has_htn else htn_excess * 0.03
    dm_adj  = dm_excess  * 0.12 if not user_has_dm  else dm_excess  * 0.04

    adjustment = htn_adj + dm_adj
    return round(max(-0.03, min(0.05, adjustment)), 4)
