/**
 * Build the system prompt and initial greeting for the Twin Chat feature.
 * Serializes only the fields needed — keeps token count reasonable.
 */

export function buildSystemPrompt(profile, input, result) {
  const name = profile?.name || "the user";
  const age = profile?.age || "unknown";
  const gender = profile?.gender || "unknown";

  const vitalScore = result?.vital_score?.current ?? result?.overall_health_score ?? "unknown";
  const vitalCategory = result?.vital_score?.category ?? "";
  const vitalMessage = result?.vital_score?.message ?? "";

  const bio = result?.biological_age;
  const bioAge = typeof bio === "object" ? bio?.biological_age : bio;
  const realAge = typeof bio === "object" ? bio?.real_age : age;
  const ageGap = typeof bio === "object" ? bio?.age_gap : null;
  const bioMessage = typeof bio === "object" ? bio?.message : "";

  const organs = result?.organs ?? {};
  const organSummary = Object.entries(organs)
    .map(([name, data]) => `${name}: ${data?.health_score ?? "?"}% health, risk ${data?.risk_level ?? "unknown"}`)
    .join("; ");

  const topRecs = (result?.priority_recommendations ?? [])
    .slice(0, 4)
    .map((r) => `[${r.priority}] ${r.action}`)
    .join("\n");

  const stressSystems = result?.body_stress?.systems ?? {};
  const stressSummary = Object.entries(stressSystems)
    .map(([k, v]) => `${k}: ${v?.level ?? v ?? "unknown"}`)
    .join(", ");

  const conditions = Array.isArray(input?.medical_conditions) ? input.medical_conditions.join(", ") : "none";
  const medications = Array.isArray(input?.medications) ? input.medications.join(", ") : "none";

  return `You are the VitalTwin AI health coach — a friendly, knowledgeable, and empathetic digital twin assistant.
You have access to ${name}'s complete health forensic report generated by the VitalTwin platform.
Your role: answer questions about their health report, explain findings in plain language, and provide actionable, personalised guidance.

IMPORTANT RULES:
- Always refer to the data in the report when answering. Never make up numbers.
- Be conversational and warm — not clinical or robotic.
- For serious concerns, recommend consulting a real doctor.
- Keep responses concise (2–4 sentences unless the user asks for detail).
- Never diagnose or prescribe. Focus on lifestyle insights and report interpretation.

## User Profile
- Name: ${name}
- Age: ${age} | Gender: ${gender}
- Height: ${profile?.height ?? "?"}cm | Weight: ${profile?.weight ?? "?"}kg
- Diet: ${profile?.diet ?? "?"} | Activity: ${profile?.activity ?? "?"}

## Health Inputs
- Smoking: ${input?.smoking ?? "?"} | Alcohol: ${input?.alcohol ?? "?"}
- Sleep: ${input?.sleep ?? "?"}h | Stress: ${input?.stress ?? "?"}
- Medical conditions: ${conditions}
- Current medications: ${medications}

## Health Report Summary
- Vital Score: ${vitalScore}/100${vitalCategory ? ` (${vitalCategory})` : ""}
- ${vitalMessage}
- Biological age: ${bioAge ?? "?"} (real age: ${realAge ?? "?"})${ageGap != null ? `, gap: ${ageGap > 0 ? "+" : ""}${ageGap} years` : ""}
- ${bioMessage}
- Organ health: ${organSummary || "not available"}
- Body stress: ${stressSummary || "not available"}

## Priority Recommendations from Report
${topRecs || "No recommendations available"}`;
}

export function buildInitialGreeting(profile, result) {
  const name = profile?.name ? profile.name.split(" ")[0] : null;
  const vitalScore = result?.vital_score?.current ?? result?.overall_health_score;
  const bio = result?.biological_age;
  const bioAge = typeof bio === "object" ? bio?.biological_age : bio;
  const realAge = typeof bio === "object" ? bio?.real_age : profile?.age;
  const ageGap = typeof bio === "object" ? bio?.age_gap : null;

  const gapText = ageGap != null
    ? ageGap > 0
      ? ` Your biological age is ${ageGap} year${ageGap !== 1 ? "s" : ""} older than your actual age — something we can work on.`
      : ageGap < 0
      ? ` Your biological age is ${Math.abs(ageGap)} year${Math.abs(ageGap) !== 1 ? "s" : ""} younger than your actual age — great work!`
      : " Your biological and chronological ages are aligned."
    : "";

  return `Hi${name ? ` ${name}` : ""}! I've reviewed your VitalTwin health report.${
    vitalScore != null ? ` Your vital score is **${vitalScore}/100**.` : ""
  }${gapText} What would you like to know about your results?`;
}
